### PR TITLE
Adding Dockerfile

### PR DESCRIPTION
**Pull request by itakenaps**
Created a dockerfile for easy deployment of flamingo

### CODE REVIEW

**Comment by tomsteele** [comment]
I'm not adverse to having a dockerfile. Should this be `golang:latest`?

**Comment by itakenaps** [comment]
I do not believe there is a latest tag for golang.

________________________________

**Comment by tomsteele** [comment]
Hmmm seems there isn't. Merging :D...

**Comment by JamesCullum** [comment]
Maybe you can build a public image as well? Wasn't able to find one.
So that we can directly pull the latest version and use it on the server.

Pipelines can do that automatically now, so it shouldn't be maintenance effort later.

**Comment by itakenaps** [comment]
I created a public repo as well. https://hub.docker.com/repository/docker/latentwhisper/flamingo

**Pull request merged**
